"""
Casos iniciais (seed cases) para bootstrap do sistema RBC.
Initial seed cases for RBC system bootstrap.
"""

SEED_CASES = [
    {
        "case_id": "seed_close_clear_shot",
        "problem_distance": 80.0,
        "problem_angle_diff": 8.0,
        "problem_npc_health": 90.0,
        "problem_player_health": 80.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "fire",
        "solution_params": '{"angle_adjustment": 0}',
        "result_success": 1,
        "result_damage_dealt": 25.0,
        "result_damage_taken": 0.0,
        "result_outcome": "hit",
        "difficulty": "Normal",
        "created_by": "seed",
        "success_rate": 0.95,
    },
    {
        "case_id": "seed_medium_pursuit",
        "problem_distance": 200.0,
        "problem_angle_diff": 25.0,
        "problem_npc_health": 85.0,
        "problem_player_health": 75.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "align_and_fire",
        "solution_params": '{"target_angle": 25.0, "speed": 0.7}',
        "result_success": 1,
        "result_damage_dealt": 15.0,
        "result_damage_taken": 5.0,
        "result_outcome": "hit",
        "difficulty": "Normal",
        "created_by": "seed",
        "success_rate": 0.80,
    },
    {
        "case_id": "seed_long_pursuit",
        "problem_distance": 350.0,
        "problem_angle_diff": 40.0,
        "problem_npc_health": 80.0,
        "problem_player_health": 70.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "pursue",
        "solution_params": '{"speed": 1.0, "rotate": true}',
        "result_success": 1,
        "result_damage_dealt": 0.0,
        "result_damage_taken": 10.0,
        "result_outcome": "moving",
        "difficulty": "Normal",
        "created_by": "seed",
        "success_rate": 0.70,
    },
    {
        "case_id": "seed_target_lost_recent",
        "problem_distance": 400.0,
        "problem_angle_diff": 60.0,
        "problem_npc_health": 75.0,
        "problem_player_health": 65.0,
        "problem_player_visible": 0,
        "problem_frames_lost": 30,
        "solution_action": "search",
        "solution_params": '{"rotation_direction": 1}',
        "result_success": 0,
        "result_damage_dealt": 0.0,
        "result_damage_taken": 0.0,
        "result_outcome": "searching",
        "difficulty": "Normal",
        "created_by": "seed",
        "success_rate": 0.50,
    },
    {
        "case_id": "seed_low_health_defensive",
        "problem_distance": 200.0,
        "problem_angle_diff": 35.0,
        "problem_npc_health": 30.0,
        "problem_player_health": 80.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "pursue",
        "solution_params": '{"speed": 0.5, "rotate": true}',
        "result_success": 1,
        "result_damage_dealt": 0.0,
        "result_damage_taken": 0.0,
        "result_outcome": "evading",
        "difficulty": "Normal",
        "created_by": "seed",
        "success_rate": 0.65,
    },
    {
        "case_id": "seed_easy_mid_range",
        "problem_distance": 150.0,
        "problem_angle_diff": 15.0,
        "problem_npc_health": 100.0,
        "problem_player_health": 100.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "align_and_fire",
        "solution_params": '{"target_angle": 15.0, "speed": 0.5}',
        "result_success": 1,
        "result_damage_dealt": 20.0,
        "result_damage_taken": 2.0,
        "result_outcome": "hit",
        "difficulty": "Easy",
        "created_by": "seed",
        "success_rate": 0.88,
    },
    {
        "case_id": "seed_hard_evasion",
        "problem_distance": 120.0,
        "problem_angle_diff": 45.0,
        "problem_npc_health": 60.0,
        "problem_player_health": 90.0,
        "problem_player_visible": 1,
        "problem_frames_lost": 0,
        "solution_action": "pursue",
        "solution_params": '{"speed": 1.0, "rotate": true}',
        "result_success": 1,
        "result_damage_dealt": 5.0,
        "result_damage_taken": 3.0,
        "result_outcome": "hit",
        "difficulty": "Hard",
        "created_by": "seed",
        "success_rate": 0.72,
    },
]


def load_seed_cases():
    """Retorna lista de seed cases para inicializar banco."""
    return SEED_CASES
